### ISSUE TITLE
VS2019 support

### ISSUE THREAD

**Issue by NN---** [beatcracker/VSCELicense#1]

**Comment by beatcracker** [comment]
I'll give it a look when it's out of the preview. Otherwise, PRs are welcome :smirk:.

**Comment by beatcracker** [comment]
Let's get the party started!

- [Microsoft launches Visual Studio 2019 for Windows and Mac](https://venturebeat.com/2019/04/02/microsoft-launches-visual-studio-2019-for-windows-and-mac/)
