### ISSUE TITLE
Modul not found

### ISSUE THREAD

**Issue by mark-baumann** [beatcracker/VSCELicense#13]
Hello,

I can't run the script without errors. Screenshot:

<img width="784" alt="Bildschirmfoto 2021-03-12 um 17 22 14" src="https://user-images.githubusercontent.com/60445235/110968392-c080ec00-8357-11eb-9eb2-3587db03e012.png">

**Comment by Biswa96** [comment]
What does the error mean in English language?

**Comment by beatcracker** [comment]
Looks like you're supplying incorrect path to the module. Try `Import-Module -Name 'C:\VSCELicense-master\VSCELicense.psd1'`, since it's where you unpacked the downloaded archive from GitHub.

**Comment by mark-baumann** [comment]
> Looks like you're supplying incorrect path to the module. Try `Import-Module -Name 'C:\VSCELicense-master\VSCELicense.psd1'`, since it's where you unpacked the downloaded archive from GitHub.

Nice now it works fine. Thanks Sir ;)
