### ISSUE TITLE
Please add VS2015 ru to script

### ISSUE THREAD

**Issue by tommy74y** [beatcracker/VSCELicense#7]
'VS2015' = 'Licenses\4D8CFBCB-2F6A-4AD2-BABF-10E28F6F2C8F\07078'

**Comment by beatcracker** [comment]
So, what you mean is that `VS2015 RU` license expiration date is not reset by the module, because it uses some other GUID?

**Comment by tommy74y** [comment]
Yes, this GUID for VS2015 Community Edition is tested in my W7ru.
U can add this GUID  to you script

**Comment by beatcracker** [comment]
Ок, давайте на русском, т.к. я не очень понимаю, что происходит :) . Такой GUID уже есть в модуле и он должен работать (#6):

- [VSCELicense.psm1#L4](https://github.com/beatcracker/VSCELicense/blob/d0eb9c4e28b617c03a42f1110497bba7e15dcb2d/VSCELicense.psm1#L4)

**Comment by tommy74y** [comment]
Можно закрывать этот вопрос.
Когда я скачал этот скрипт (2 дня назад) этой строки 
'VS2015' = 'Licenses\4D8CFBCB-2F6A-4AD2-BABF-10E28F6F2C8F\07078'
не было в VSCELicense-master.zip
Спасибо!

**Comment by beatcracker** [comment]
Очень странно, PR с поддержкой VS2015 был влит аж 16 марта. Чудеса...

В любом случае и вам спасибо, закрываю раз всё работает.
