### ISSUE TITLE
License Location

### ISSUE THREAD

**Issue by YoRHa-A5** [beatcracker/VSCELicense#9]
Hey, thanks for the program.

Where can I find the exact location of the license for VSCE 2019?
Tried different files in different locations but none seem to work.

Thanks in advance.

**Comment by beatcracker** [comment]
I think you misinterpreted usage instructions. The `X:\PATH\TO\VSCELicense` is the path where you cloned this repo. You actually need to give `Import-Module` path to the `VSCELicense.psd1` or path to the folder containing it without trailing slash.

Example (assuming you've cloned/downloaded this repo to `C:\VSCELicense`)
- `Import-Module -Name C:\VSCELicense`
--or--
- `Import-Module -Name C:\VSCELicense\VSCELicense.psd1`

**Comment by YoRHa-A5** [comment]
Ohh, RIP xD
Thanks for clarifying 👍

**Comment by beatcracker** [comment]
No problem, I'll try to make it more clear in the readme.
